config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :users, controllers: { registrations: 'user/registrations' }  
  
  devise_scope :user do 
    authenticated :user do 
      root 'forums#index'
    end
    unauthenticated do 
      root to: 'pages#index'
    end
  end

 
  resources :forums do
    member do
     put "like", action: :upvote
     put "dislike", action: :downvote
    end
    resources :comments, only: [:create, :destroy]
  end
end

app/models/forum.rb
class Forum < ApplicationRecord
    belongs_to :user
    acts_as_votable
    has_many :comments
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :set_forum, only: [:show, :edit, :update, :destroy]
  
  # GET /forums
  def index
    @forums = Forum.all
  end

  # GET /forums/1
  def show
  end

  # GET /forums/new
  def new
    @forum = current_user.forums.build
  end

  # GET /forums/1/edit
  def edit
  end

  # POST /forums
  def create
    @forum = current_user.forums.build(forum_params)
    if @forum.save
      redirect_to @forum, notice: 'Forum was successfully posted.'
    else
      render :new
    end
  end

  # PATCH/PUT /forums/1
  def update
    if @forum.update(forum_params)
      redirect_to @forum, notice: 'Forum was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /forums/1
  def destroy
    @forum.destroy
    redirect_to forums_url, notice: 'Forum was successfully destroyed.'
  end

  def upvote 
    @forum = Forum.find(params[:id])
    @forum.upvote_by current_user
    redirect_to forums_path
  end  
  
  def downvote
    @forum = Forum.find(params[:id])
    @forum.downvote_by current_user
    redirect_to forums_path
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum
      @forum = Forum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_params
      params.require(:forum).permit(:title, :url, :description)
    end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.erb
<%= form_with(model: forum, remote: true) do |form| %>
  <% if forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(forum.errors.count, "error") %> prohibited this forum from being saved:</h2>
      <ul>
      <% forum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>
<div class="form-group">
    <%= form.label :url %><br>
    <%= form.text_field :url, class: "form-control" %>
  </div>
<div class="form-group">
    <%= form.label :description %><br>
    <%= form.text_area :description, class: "textarea" %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit "Post", class: "btn btn-kg btn-primary" %>
  </div>
<% end %>

app/views/forums/edit.html.erb
<div id="main_content" class="container">
<div id="content" class="col-md-9 center-block">

<h1>Editing Forum</h1>

<%= render 'form', forum: @forum %>

<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<section class="hero is-primary" id= "forum_hero">
  <div class="hero-body">
    <h1 id= "forum-heading"> Forums </h1>
      <h2 id= "forum-heading-subtitle"> Community building for teachers! </h2>
        <p class="control" id= "new-forum">
          <%= link_to 'Click to Post', new_forum_path, class: "button is-warning" %>
        </p>
  </div>
</section>



<div id="main_content" class="container">
<div id="content" class="col-md-9 center-block">

  <div class="columns is-multiline is-mobile">
  <%# <div class="column is-one-quarter">

  </div> %>

  <div class="column">
   <div class="tabs is-centered">
  <ul>
    <li><a>General</a></li>
    <li><a>Lessons</a></li>
    <li><a>Classroom Management</a></li>
    <li><a>Brags</a></li>
    <li><a>Help Wanted</a></li>
  </ul>
  </div>


<% @forums.each do |forum| %>
  <article class="media">
    <figure class="media-left">
      <% if forum.user.avatar.attached? %>
        <p class="image is-64x64">
          <%= image_tag(forum.user.avatar) %>
        </p>
      <% end %>
    </figure>
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= link_to forum.title, forum %></strong> <small><%= forum.user.username %></small> <small><%= time_ago_in_words(forum.created_at) %> ago</small>
         
    <div class="btn-group">
        <a class="btn btn-default btn-sm" href="<%= forum.url %>">Visit Link</a>
        <%= link_to like_forum_path(forum), method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon"></span>👍
        <%= forum.get_upvotes.size %>
        <% end %>

        <%= link_to dislike_forum_path(forum), method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon"></span>👎
        <%= forum.get_downvotes.size %>
        <% end %>
      </div>

        </p>
      </div>
    </div>

  </article>
<% end %>

  </div>
</div>



<div class="column">

<nav class="pagination" role="navigation" aria-label="pagination">
  <a class="pagination-previous" title="This is the first page" disabled>Previous</a>
  <a class="pagination-next">Next page</a>
  <ul class="pagination-list">
    <li>
      <a class="pagination-link is-current" aria-label="Page 1" aria-current="page">1</a>
    </li>
    <li>
      <a class="pagination-link" aria-label="Goto page 2">2</a>
    </li>
    <li>
      <a class="pagination-link" aria-label="Goto page 3">3</a>
    </li>
  </ul>
</nav>

  </div>

app/views/forums/new.html.erb
<div id="main_content" class="container">
<div id="content" class="col-md-9 center-block">

<h1>New Forum</h1>

<%= render 'form', forum: @forum %>
<br>
<%= link_to 'Back to Forums', forums_path %>

app/views/forums/show.html.erb
<div id="main_content" class="container">
<div id="content" class="col-md-9 center-block">

<div class="page-header">
 <h1><a href="<%= @forum.url %>"><%= @forum.title %></a><br> <small>Submitted by <%= @forum.user.username %></small></h1>
 <div> <h3>Description: </h2> <%= @forum.description %>
 </div>

</div>
<div class="btn-group">
 <%= link_to 'Visit URL', @forum.url, class: "btn btn-primary" %>
</div>
<% if @forum.user == current_user %>
 <div class="btn-group">
  <%= link_to 'Edit', edit_forum_path(@forum), class: "btn btn-default" %>
  <%= link_to 'Delete', @forum, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
 </div>
<% end %>

<div class="btn-group pull-right">
 <%= link_to like_forum_path(@forum), method: :put, class: "btn btn-default btn-sm" do %>
  <span class="glyphicon"></span>
  👍
  <%= @forum.get_upvotes.size %>
 <% end %>
 <%= link_to dislike_forum_path(@forum), method: :put, class: "btn btn-default btn-sm" do %>
  <span class="glyphicon"></span>
  👎
  <%= @forum.get_downvotes.size %>
 <% end %>
</div>



<h3 class="comments_title">
 <%= @forum.comments.count %> comments
</h3>


<div id="comments">
 <%= render :partial => @forum.comments %>
</div>
<%= simple_form_for [@forum, Comment.new], remote: true do |f| %>
 <div class="field">
  <%= f.text_area :body, class: "form-control" %>
 </div>
 <br>
 <%= f.submit "Add Comment", class: "btn btn-primary" %>
<% end %>