config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :users, controllers: { registrations: 'user/registrations' }  
  
  devise_scope :user do 
    authenticated :user do 
      root 'forums#index'
    end
    unauthenticated do 
      root to: 'pages#index'
    end
  end

 
  resources :forums do
    member do
     put "like", action: :upvote
     put "dislike", action: :downvote
    end
    resources :comments, only: [:create, :destroy]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :forum
  belongs_to :event
  validates :user_id, presence: true
  validates :body, presence: true
  validates :event_id, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:destroy]

  # POST /comments
  def create
    @forum = Forum.find(params[:forum_id])
    @comment = @forum.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to @comment.forum, notice: 'Comment was successfully created.'
    else
      format.html { render :new }        
    end
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy
    redirect_to @comment.forum, notice: 'Comment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:forum_id, :body, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
 <div class="comments_wrapper clearfix">
  <div class="pull-left">
   <p class="lead"><%= comment.body %></p>
   <p><small>Submitted <strong><%= time_ago_in_words(comment.created_at) %> ago</strong> by <%= comment.user.email %></small></p>
  </div>
<div class="btn-group pull-right">
   <% if comment.user == current_user %>
    <%= link_to 'Destroy', [comment.forum, comment], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-default" %>
    <% end %>
  </div>
 </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: comment, remote: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :forum_id %>
    <%= form.number_field :forum_id %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
$(".comment_text").val('');
$(".comment_list").append("<%= j render @comment %>");
$("#comment_<%= @comment.id %>").hide().fadeIn(800);
$("#comment_count").text("Comments (<%= @comment.event.comments.count %>)");

app/views/comments/destroy.js.erb
$("#comment_<%= @comment.id %>").fadeOut(500, function(){
	$(this).remove();
})
$("#comment_count").text("Comments (<%= @comment.event.comments.count %>)");

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', forums_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Forum</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.forum_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Forum:</strong>
  <%= @comment.forum_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>